services:
  api:
    build: .
    restart: always
    hostname: api
    env_file:
      - .development.docker.env
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: root
      POSTGRES_DB: best-app
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: