services:
  api:
    build: .
    restart: always
    hostname: api
    environment:
      PORT: 9000
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: best-app
      MEAL_API_URL: https://www.themealdb.com
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    hostname: postgres
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: root
      POSTGRES_DB: best-app
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
